apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s74rqbsy4-nodejs-gitops
  description: This is GitOps manifest for s74rqbsy4-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: s74rqbsy4-nodejs
    janus-idp.io/tekton: s74rqbsy4-nodejs
    backstage.io/kubernetes-id: s74rqbsy4-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s74rqbsy4-nodejs
